[package]
name = "empire-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
gloo-timers = "0.3"

[dependencies.web-sys]
version = "0.3"
features = [
  "Window",
  "Document",
  "HtmlCanvasElement",
  "CanvasRenderingContext2d",
  "WebSocket",
  "MessageEvent",
  "KeyboardEvent",
  "MouseEvent",
  "Performance",
  "BinaryType",
  "Blob",
  "ErrorEvent",
  "CloseEvent",
  "EventTarget",
  "Element",
  "DomRect",
  "TextMetrics",
  "console",
  "Location",
  "HtmlElement",
  "CssStyleDeclaration",
]

[profile.release]
opt-level = "s"
lto = true
